CREATE TABLE [Meta].[Item] (
    [ItemID]                            INT                                                IDENTITY (1, 1) NOT NULL,
    [ItemName]                          VARCHAR (100)                                      NOT NULL,
    [ItemDescription]                   VARCHAR (1000)                                     NULL,
    [ItemTypeID]                        SMALLINT                                           NOT NULL,
    [ConnectionID]                      INT                                                NOT NULL,
    [ProjectID]                         INT                                                NOT NULL,
    [TableCompressionType]              VARCHAR (5)                                        NULL,
    [TableLateArriving]                 BIT                                                NULL,
    [TableExternalPartitionScheme]      VARCHAR (50)                                       NULL,
    [TablePartitionSchemeName]          VARCHAR (50)                                       NULL,
    [TablePartitionColumnName]          VARCHAR (50)                                       NULL,
    [FlatFileExtension]                 VARCHAR (10)                                       NULL,
    [FlatFileType]                      VARCHAR (15)                                       NULL,
    [FlatFileIsUnicode]                 BIT                                                NULL,
    [FlatFileLocale]                    VARCHAR (15)                                       NULL,
    [FlatFileCodePage]                  INT                                                NULL,
    [FlatFileTextQualifer]              VARCHAR (15)                                       NULL,
    [FlatFileHeaderRowDelimiter]        VARCHAR (15)                                       NULL,
    [FlatFileHeaderRowsToSkip]          INT                                                NULL,
    [FlatFileColumnNamesInFirstDataRow] BIT                                                NULL,
    [FlatFileColumnDelimiter]           VARCHAR (15)                                       NULL,
    [FlatFileRowDelimiter]              VARCHAR (15)                                       NULL,
    [FlatFileDataRowsToSkip]            INT                                                NULL,
    [SSISLoadPattern]                   VARCHAR (20)                                       NULL,
    [SSISParallelDataFlows]             TINYINT                                            NULL,
    [SSISParallelDataFlowsColumn]       VARCHAR (50)                                       NULL,
    [ValidFrom]                         DATETIME2 (7) GENERATED ALWAYS AS ROW START HIDDEN NOT NULL,
    [ValidTo]                           DATETIME2 (7) GENERATED ALWAYS AS ROW END HIDDEN   NOT NULL,
    CONSTRAINT [PK_Item] PRIMARY KEY CLUSTERED ([ItemID] ASC),
    CONSTRAINT [FK_Item_ItemType] FOREIGN KEY ([ItemTypeID]) REFERENCES [Meta].[ItemType] ([ItemTypeID]),
    CONSTRAINT [FK_Item_Project] FOREIGN KEY ([ProjectID]) REFERENCES [Meta].[Project] ([ProjectID]),
    CONSTRAINT [UQ_Item] UNIQUE NONCLUSTERED ([ItemName] ASC),
    PERIOD FOR SYSTEM_TIME ([ValidFrom], [ValidTo])
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE=[Meta].[Item_History], DATA_CONSISTENCY_CHECK=ON));

