CREATE PROCEDURE [AWLTSRC].[CustomerPostLoad_HASH]
AS
BEGIN

SET NOCOUNT ON;

EXECUTE [AWLTSRC].[CustomerDelete];
EXECUTE [AWLTSRC].[CustomerUpdate];
EXECUTE [AWLTSRC].[CustomerInsert];


RETURN 0
END